### ISSUE TITLE
Youtube streams do not work.

### ISSUE THREAD

**Issue by chipyzs** [woutervanwijk/Mopidy-MusicBox-Webclient#102]
Youtube / soundcloud streams do not load, I add them but they do not show up on the queue. The local and the radio function works fine but the youtube bit does not.

**Comment by kingosticks** [comment]
They load just fine for me. What URI are you putting into the streams box? For youtube I don't think you can just use the normal HTTP URI like you would in a web browser. For example, for youtube video https://www.youtube.com/watch?v=aAst-vyasiM, you would enter `yt:aAst-vyasiM`. Sometimes it takes a little while to load and start playing. 

soundcloud should just work with the normal webpage URL.

**Comment by chipyzs** [comment]
@kingosticks I was using the normal url but i have tried yt:aAst-vyasiM and aAst-vyasiM but they do not load / play.

**Comment by kingosticks** [comment]
You must have yt: in front so mopidy knows to use the youtube backend to
load the content. If you look in the Mopidy log you may find error messages
explaining why it's not playing for you. It certainly worked for me.

**Comment by javaj0hn** [comment]
I'm also running into this issue with youtube & soundcloud. I've monitored the Mopidy logs but nothing relevant came up. I've been trouble shooting for an hour now so I'll update this if I find anything out.

I'm running Ubuntu 12.04 LTS

**Comment by kingosticks** [comment]
@javaj0hn, Just to be clear, do youtube and soundcloud streams work from the search results?

**Comment by javaj0hn** [comment]
@kingosticks Just saw this was a feature. No they do not load any search results.

**Comment by kingosticks** [comment]
In which case this doesn't sound like a webclient issue. 

You should ensure the extensions are definitely loaded and enabled, this should be clear in the log file. `mopidy deps` and `mopidy config` might also help you determine this.

**Comment by javaj0hn** [comment]
My deps & config are as follows - http://pastebin.com/cTggGkir

I feel that I am mis-configuring something with the websockets.

**Comment by kingosticks** [comment]
There is nothing to configure for websockets for normal users. And normally you would not set `musicbox = true` either.

Neither Mopidy-Soundcloud or Mopidy-Youtube exist in your deps or your config which shows that Mopidy is not finding them on your system. Are you sure they are installed? Have a look at https://docs.mopidy.com/en/latest/installation/debian/#missing-extensions and  https://docs.mopidy.com/en/latest/debian/#differences-when-running-as-a-system-service

**Comment by kingosticks** [comment]
Did you get this working? I don't think there is a webclient issue here.

**Comment by javaj0hn** [comment]
Hey apologies, just saw this updated. Yes I got it working, I was missing the youtube and spotify deps. All solved.

**Comment by kingosticks** [comment]
That's great and no worries.
