### ISSUE TITLE
Feature: Ability to save playlist

### ISSUE THREAD

**Issue by DavisNT** [woutervanwijk/Mopidy-MusicBox-Webclient#106]
I would like to add ability to save queue as local playlist.

Queue could have a _Save_ button next to _Clear_ button. _Save_ button would open an input prompt with playlist name and save it as local playlist.

:question: Is such feature welcome? If yes, I will investigate it and, possibly, create a Pull Request.

**Comment by kingosticks** [comment]
Yes, sounds good to me.

**Comment by DavisNT** [comment]
Okie, I will look what I can do for this. :+1:

**Comment by kingosticks** [comment]
Merged in https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/commit/ab59c7be007953de08f2f25287b0655c4bcc7ce0
