### ISSUE TITLE
Can't press any buttons

### ISSUE THREAD

**Issue by maemigh** [woutervanwijk/Mopidy-MusicBox-Webclient#115]
Wasn't able to re-open issue #105 

I'm having this issue as well. There appear to be some javascript errors after I upgrade to webclient 2.0.0. I've confirmed that the var isMusicBox line is what is stopping me from pressing any buttons (I just set it to true in my local file and now everything works).

index.html line 16: Uncaught SyntaxError: Unexpected token {

16: var isMusicBox = {{musicbox}}; // Remove MusicBox only content (e.g. settings, system pages)

**Comment by kingosticks** [comment]
That issue is not closed, so let's use that.
