### ISSUE TITLE
Update interface for easier use of different services

### ISSUE THREAD

**Issue by woutervanwijk** [woutervanwijk/Mopidy-MusicBox-Webclient#24]
The webinterface would be better if you could browse/search within different services (mopidy extensions), like Spotify, Google Music, Local, Podcasts, etc

Liket this: https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xfp1/v/t1.0-9/p180x540/1974986_686711361368359_8019291498242019323_n.png?oh=ff77f892ecd7941d36ed8ac3c2d79f9a&oe=54CB3183&__gda__=1417895665_057dc9823ed44861ed6b5d6b320f76c8

Also Dirble/Tunein/etc should be integrated in the Radio part

**Comment by kingosticks** [comment]
So it seems extension specific searching was implemented at some point - closing.
