### ISSUE TITLE
mopidy-musicbox-webclient not found

### ISSUE THREAD

**Issue by dorel14** [woutervanwijk/Mopidy-MusicBox-Webclient#278]
Hello 
i've tryied t install and the result is not as good as i tought 
~~~
root@raspberrypi2:/home/pi# python3 -m pip install Mopidy-MusicBox-Webclient
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Mopidy-MusicBox-Webclient
  Downloading https://www.piwheels.org/simple/mopidy-musicbox-webclient/Mopidy_MusicBox_Webclient-2.6.0-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 989 kB/s
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from Mopidy-MusicBox-Webclient) (39.0.1)
Requirement already satisfied: Mopidy>=1.1.0 in /usr/local/lib/python3.6/site-packages (from Mopidy-MusicBox-Webclient) (2.1.0)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python3.6/site-packages (from Mopidy>=1.1.0->Mopidy-MusicBox-Webclient) (2.23.0)
Requirement already satisfied: tornado>=3.2 in /usr/local/lib/python3.6/site-packages (from Mopidy>=1.1.0->Mopidy-MusicBox-Webclient) (6.1)
Requirement already satisfied: Pykka>=1.1 in /usr/local/lib/python3.6/site-packages (from Mopidy>=1.1.0->Mopidy-MusicBox-Webclient) (2.0.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.0->Mopidy>=1.1.0->Mopidy-MusicBox-Webclient) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.0->Mopidy>=1.1.0->Mopidy-MusicBox-Webclient) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.0->Mopidy>=1.1.0->Mopidy-MusicBox-Webclient) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.0->Mopidy>=1.1.0->Mopidy-MusicBox-Webclient) (2.9)
Installing collected packages: Mopidy-MusicBox-Webclient
Successfully installed Mopidy-MusicBox-Webclient-2.6.0
root@raspberrypi2:/home/pi# mopidyctl deps
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
WARNING  [MainThread] mopidy.config Config file file:///etc/mopidy/mopidy.conf has errors; line 11, 12, 13, 14, 15, 16 has been ignored
WARNING  [MainThread] mopidy.config Ignoring config section 'musicbox_webclient' because no matching extension was found
Executable: /usr/bin/mopidy
Platform: Linux-5.4.79+-armv6l-with-debian-10.7
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
Mopidy-Scrobbler: 2.0.1 from /usr/lib/python3/dist-packages
Mopidy-MPD: 3.1.0 from /usr/lib/python3/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
~~~
try also apt 
root@raspberrypi2:/home/pi# apt search mopidy
En train de trier... Fait
Recherche en texte intégral... Fait
gir1.2-playerctl-2.0/stable 2.0.1-1 armhf
  utility to control media players via MPRIS (gir bindings)

libplayerctl-dev/stable 2.0.1-1 armhf
  utility to control media players via MPRIS (development files)

libplayerctl-doc/stable 2.0.1-1 all
  utility to control media players via MPRIS (documentation)

libplayerctl2/stable 2.0.1-1 armhf
  utility to control media players via MPRIS (library)

mopidy/stable,now 3.1.1-1 all  [installé]
  extensible music server

mopidy-alsamixer/stable 2.0.1-1 all
  Mopidy extension for volume control via ALSA

mopidy-beets/stable 4.0.1-1 all
  Mopidy extension for playing music from Beets' web plugin

mopidy-dirble/stable 1.3.0-3 all
  Mopidy extension for browsing Dirble's radio station directory

mopidy-dleyna/stable 2.0.1-2 all
  Mopidy extension for playing music from Digital Media Servers

mopidy-doc/stable 3.1.1-1 all
  extensible music server - documentation

mopidy-internetarchive/stable 3.0.0-2 all
  Mopidy extension for playing music from the Internet Archive

mopidy-local/stable 3.2.0-1 all
  Mopidy extension for playing music from your local music archive

mopidy-local-sqlite/stable 1.0.0-2 all
  Mopidy extension for keeping your local library in SQLite

mopidy-mpd/stable,now 3.1.0-1 all  [installé]
  Mopidy extension for controlling Mopidy from MPD clients

mopidy-mpris/stable 3.0.3-1 all
  Mopidy extension for controlling playback through MPRIS

mopidy-podcast/stable 3.0.0-2 all
  Mopidy extension for searching and browsing podcasts

mopidy-podcast-gpodder/stable 1.0.0-1 all
  Mopidy extension for searching and browsing gpodder.net podcasts

mopidy-podcast-itunes/stable 3.0.0-2 all
  Mopidy extension for searching and browsing iTunes podcasts

mopidy-scrobbler/stable,now 2.0.1-1 all  [installé]
  Mopidy extension for scrobbling music to Last.fm

mopidy-somafm/stable 2.0.0-2 all
  Mopidy extension for playing music from SomaFM

mopidy-soundcloud/stable 3.0.1-1 all
  Mopidy extension for playing music from SoundCloud

mopidy-spotify/stable 4.1.0-0mopidy1 all
  Mopidy extension for playing music from Spotify

mopidy-tunein/stable 1.0.2-1 all
  Mopidy extension for playing music from TuneIn

mopidy-youtube/stable 2.0.0-2 all
  Mopidy extension for playing music from YouTube

playerctl/stable 2.0.1-1 armhf
  utility to control media players via MPRIS

snapserver/stable 0.15.0-1 armhf
  Snapcast server

**Comment by kingosticks** [comment]
This install/system is messed up.
> Successfully installed Mopidy-MusicBox-Webclient-2.6.0

This version is old and not supported. The latest version (which should be being installed through pip) is [v3.1.0](https://github.com/pimusicbox/mopidy-musicbox-webclient/releases). But for some reason your system is trying to install an ancient version of Mopidy-MusicBox-Webclient under an ancient version of Python 3 (Python 3.6), the result of that is your system's `python3` interpreter (Python 3.7) being unable to find it. I don't know how your system got in this state but maybe you can workaround the issue by installing using `python3.7 -m pip install Mopidy-MusicBox-Webclient`. I'd also suggest removing all traces of of Mopidy and Mopidy-Musicbox-Webclient under /usr/local/lib/python3.6/site-packages/ as they will not work. 

```
pi@testpi:~ $ which python3
/usr/bin/python3
pi@testpi:~ $ /usr/bin/python3 --version
Python 3.7.3

pi@testpi:~ $ sudo mopidyctl deps
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
Executable: /usr/bin/mopidy
Platform: Linux-5.4.79-v7+-armv7l-with-debian-10.7
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
Mopidy-MusicBox-Webclient: 3.1.0 from /usr/local/lib/python3.7/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Mopidy: 3.1.1 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
Mopidy-MPD: 3.1.0 from /usr/lib/python3/dist-packages
Mopidy-Spotify: 4.1.0 from /usr/lib/python3/dist-packages
Mopidy-Local: 3.2.0 from /usr/lib/python3/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
```

**Comment by dorel14** [comment]
Thx , it's now working
