### ISSUE TITLE
Musicbox button to stop playing a song doesn’t work anymore

### ISSUE THREAD

**Issue by mgrouch** [woutervanwijk/Mopidy-MusicBox-Webclient#280]
See also
https://github.com/mopidy/mopidy/issues/1987

**Comment by kingosticks** [comment]
What "stop" button exactly? There is a "pause" button and that works just fine still. Re-open this if/when you can provide a debug log and your version information because I do not know what you mean.

**Comment by mgrouch** [comment]
'Pause' button doesn't pause.

**Comment by kingosticks** [comment]
Please provide a [debug log and your deps and your config](https://docs.mopidy.com/en/latest/troubleshooting/) because I cannot reproduce.
