### ISSUE TITLE
Clearing the queue also deletes current playing track

### ISSUE THREAD

**Issue by vrs01** [woutervanwijk/Mopidy-MusicBox-Webclient#56]
Hi!

When clearing the queue also the current playing track is stopped. I would prefer to keep the current song playing while putting new music into the queue. What do you think?

I use the Musicbox 0.5.1 RC2. I like this version a lot!

**Comment by kingosticks** [comment]
Yep sorry, you are 100% right and it's still exactly how it works. When the tracklist (current playlist) changes and the currently playing song is not in the tracklist, then playback stops.
