### ISSUE TITLE
Youtube link not working for non Pi MusicBox installation

### ISSUE THREAD

**Issue by R00t8ug** [woutervanwijk/Mopidy-MusicBox-Webclient#59]
A lot bug for non Pi MusicBox Installation.

**Comment by srodrig0209** [comment]
Yeah, I'm seeing the same thing. If I use `moped` or `kuechenradio` youtube results from https://github.com/dz0ny/mopidy-youtube show up just fine, but as soon as I switch back to musicbox, the results are slow to load and the individual track listing fails to show up.

**Comment by kingosticks** [comment]
Works just fine for me, please reopen with more specifics is this is still a problem.
