### ISSUE TITLE
Keyboard shortcut blocking

### ISSUE THREAD

**Issue by akkenoth** [woutervanwijk/Mopidy-MusicBox-Webclient#63]
Currently, MusicBox web interface blocks all keyboard shortcuts (like ctrl+tab, alt+w etc).

Expected behaviour would be only blocking these keyboard actions, that MusicBox overrides (ie space for pause/play).

Fix:
@mopidy_musicbox_webclient/static/js/gui.js:509
```
$(document).keypress( function (event) {
    //console.log('kp: '+event);
    if (event.target.tagName != 'INPUT') {
-       event.preventDefault();
        switch(event.which) {
            case 32:
                doPlay();
+               event.preventDefault();
                break;
            case '>':
                doNext();
+               event.preventDefault();
                break;
            case '<':
                doPrevious();
+               event.preventDefault();
                break;
        }
    return true;
    }
});
```

**Comment by kingosticks** [comment]
This must be browser specific as those shortcuts work perfectly for me using Chrome Version 38.0.2125.111 (64-bit) on Linux Mint.

**Comment by akkenoth** [comment]
As far as I understand the [specification](https://developer.mozilla.org/en-US/docs/Web/Events/keydown#preventDefault%28%29_of_keydown_event), preventDefault() should prevent all actions on particular event.

It is indeed browser specific, but in a reverse-ish manner: Chrome simply blocks preventDefault() on some keyboard events (see [this](http://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w)).
I'm using Firefox (according to JS compliancy pages, version and OS are irrelevant), but other browsers like Safari/IE/etc can possibly have this issue too.

**Comment by kingosticks** [comment]
Fair enough, just wanted to highlight the fact that verifying any fix would require a particular browser. 
If you can submit a pull request then it's nice and easy for @woutervanwijk

**Comment by kingosticks** [comment]
Fixed in https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/commit/13c024464388fed85d060edbfe746926f1353a37
