### ISSUE TITLE
Adding to the queue from the browse page

### ISSUE THREAD

**Issue by EHLOVader** [woutervanwijk/Mopidy-MusicBox-Webclient#68]
It doesn't appear to be an option to add to the queue with the menu from the browse pages.

**Comment by wagamama** [comment]
PR #82 for this enhancement

**Comment by kingosticks** [comment]
Fixed in https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/commit/e440dc4d5460a9de321454d92850e7b221f24c3b
