### ISSUE TITLE
Add alt or title text to all controls to allow hover hints

### ISSUE THREAD

**Issue by EHLOVader** [woutervanwijk/Mopidy-MusicBox-Webclient#76]
Make it possible to hover over any of the controls for an explicit hint of what it does. Most are intuitive but this would go a long way towards usability imho.

**Comment by kingosticks** [comment]
Fixed in https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/commit/941fac19e87589bd28630ffb6f04f10503100e33
