### ISSUE TITLE
Multiple currently playing songs in queue

### ISSUE THREAD

**Issue by kingosticks** [woutervanwijk/Mopidy-MusicBox-Webclient#81]
If the same track appears in the queue multiple times, all instances of it will be highlighted as the currently playing track (with a little play icon).

**Comment by wagamama** [comment]
To handle this case, need to use TlTracks instead of Tracks. Remove one of duplicated songs shall be handled in the same way or all duplicated songs are removed.

**Comment by kingosticks** [comment]
Yeh, it turns out there's a whole bunch of occurrences of this bug. The way we (incorrectly) figure out what's the currently playing song for the "play track next" functionality also suffers from this. They all need use a common function and for that function to use TlTracks, as you say.

**Comment by wagamama** [comment]
I resolve this issue in PR #88.
Please check this PR, thanks.
