### ISSUE TITLE
Slow to play track when browsing a folder containing many tracks

### ISSUE THREAD

**Issue by kingosticks** [woutervanwijk/Mopidy-MusicBox-Webclient#85]
Originally posted at https://discuss.mopidy.com/t/browse-folders-single-track-takes-like-minutes-to-start-playing/619

> I noticed that when I browse the folders and pick a song that is located in a folder with few other songs (7) then this song starts playing almost immediately.

>However, if I pick a song that is located in a folder with about 40 other songs, then it takes way too long to listen to such a song spontaneously (feels like it takes minutes, probably it is only one minute delay effectively).

> When checking the Queue page, I noticed that Pi MusicBox not only enqueues the chosen song, but the entire folder. Maybe this is why it takes longer for songs from larger folders.

I thought we had previously fixed this but seems that was just for playlists.

**Comment by wagamama** [comment]
I try to resolve this issue in PR #94

**Comment by kingosticks** [comment]
The issue is https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/blob/develop/mopidy_musicbox_webclient/static/js/controls.js#L65

**Comment by kingosticks** [comment]
Fixed in https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/commit/bf0ad633179e950504e2e6464889f59b157d126d.
