### ISSUE TITLE
Download/Make playlist option with youtube songs

### ISSUE THREAD

**Issue by itay13-meet** [woutervanwijk/Mopidy-MusicBox-Webclient#87]
Hey.
I haven't seen any way to make playlists with youtube songs.

I tried to save my queue, or use youtube's playlist, but with no success

Anyone knows if there is any option for that?
Thank you.

**Comment by kingosticks** [comment]
Saving the queue is not yet possible.

Playing a youtube playlist should be possible. Have you looked at https://github.com/dz0ny/mopidy-youtube#how-to-use ?

**Comment by itay13-meet** [comment]
I tried to it in the search page, my search was this:
yt:http://www.youtube.com/playlist?list=PL0AE8EBD3F68E3788

It didn't find anything and nothing chaged... any ideas why?

**Comment by kingosticks** [comment]
You can goto the streams page and enter 'yt:https://www.youtube.com/playlist?list=PL0AE8EBD3F68E3788' in the top URI box.

**Comment by itay13-meet** [comment]
I tried it, it doesn't work either.

**Comment by kingosticks** [comment]
Worked for me. Check you are running the latest version. And check you are giving you tube enough time to load, it can be a bit slow.

**Comment by itay13-meet** [comment]
It's working! I just had to wait (It took around 1 min) thanks for the help, and for developing RPI 2 version, both helped me alot! 
Itay
