### ISSUE TITLE
Shuffle mode for queue

### ISSUE THREAD

**Issue by SLv99** [woutervanwijk/Mopidy-MusicBox-Webclient#90]
Is it possible to add a shuffle mode for the queue?

**Comment by kingosticks** [comment]
One of the icons at the bottom left will enable it.

**Comment by SLv99** [comment]
Thanks, I was looking on the queue page.

**Comment by kingosticks** [comment]
Yeh it does really belong on the queue page. And for anyone in the future
looking for this, I should have said bottom right.
