### ISSUE TITLE
Keyboard shortcuts - remapping and global shortcuts

### ISSUE THREAD

**Issue by flecmart** [woutervanwijk/Mopidy-MusicBox-Webclient#92]
Hi,

it would be cool to have an option for remapping keyboard shortcuts. The idea is to have the ability to globally use i.e. a keyboard's media buttons while the webinterface is opened (in the background).

For now shortcuts are:
"space" = play/pause
">" = next track
"<" = previous track

Shortcuts for changing and/or mute volume would be nice, too.

Is there a way to do that? As I am an computer science student maybe I can contribute somehow?

**Comment by adamcik** [comment]
Web pages don't have access to global shortcuts.

However, at least for chrome extensions / apps do - https://developer.chrome.com/extensions/commands#scope So someone could make a mopidy chrome extension for shortcuts.

**Comment by adamcik** [comment]
Of course if this is just for when the page has focus it is a different story :-)

**Comment by kingosticks** [comment]
Sorry, yes I was assuming the browser page had focus. The current shortcut keys obviously only work when this is the case.

**Comment by kingosticks** [comment]
Although if you really wanted global shortcuts you could probably knock something together using your systems shortcut key mapper and mpc.

**Comment by kingosticks** [comment]
Sooo, is there anything for us to do here?

**Comment by flecmart** [comment]
did not have time to look into this again by now. what is the mpc you are talking about @kingosticks? maybe I'll have a look into chrome extension developing... but I do not really know where to start right know.

**Comment by kingosticks** [comment]
http://linux.die.net/man/1/mpc

So you would use your operating system's tools to globally bind keyboard combinations to whatever commands you want. i.e. bind ctrl+F3 to 'mpc next'. Or for more exotic commands, instead of using mpc, call the Mopidy HTTP API directly using curl.

**Comment by flecmart** [comment]
Thank you!

If I got it right, mpc is no option for me, because one of my controlling pcs is running windows.

However, calling the HTTP API with curl and mapping it as a globally shortcut sounds like an easy solution.

A corresponding curl command would be something like this?

curl -X POST -H Content-Type:application/json -d '{ "method": "core.library.refresh", "jsonrpc": "2.0", "params": { "uri": null }, "id": 1 }' http://localhost:6680/mopidy/rpc

Found this in another thread... So I can just change the method and params part to the right API functions I want to use? Plus, changing the host to the raspberry pi's ip in my local setup?

**Comment by kingosticks** [comment]
mpc used to build on Windows but they do appear to have stopped providing Windows binaries. But if you're up for using the HTTP API then it's much more powerful anyway. 

Yep, that's it. https://github.com/dz0ny/mopidy-api-explorer will probably be useful too.
