### ISSUE TITLE
Question: Can I play a stream making a request to a URL?

### ISSUE THREAD

**Issue by camilonova** [woutervanwijk/Mopidy-MusicBox-Webclient#97]
I would like to play a new stream from my command line. Can I make a request to a URL sending the stream URL to make it work?

**Comment by kingosticks** [comment]
You can send requests to Mopidy's http interface using something like curl
or to the MPD interface using mpc. The Mopidy and mpc documentation should
provide you with the necessary commands for whichever way you decide to do
it. Is this question particularly relevant to musicbox-webclient ? If not,
you're better off posting at discuss.mopidy.com.

**Comment by camilonova** [comment]
You were right, thank you.
